import { Inter } from "next/font/google";
import styles from './layout.module.scss';

const inter = Inter( { subsets: ["latin"] } );

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout( { children } ) {
    return (
        <html lang="en">
        <body className={styles.bodyMain}>{children}</body>
        </html>
    );
}
